project:
  type: book
  execute-dir: project
  pre-render:
    - scripts/mit_press/generate_figure_list.py --clear
  post-render:
    - scripts/clean_svgs.py
    - scripts/mit_press/generate_figure_list.py
  preview:
    browser: true
    navigate: true

execute:
  freeze: false
  env:
    PYTHONPATH: "."
