format:
  pdf:
    include-in-header:
      - text: |
          % Add "COPYEDIT" watermark to each page
          \usepackage{draftwatermark}
          \SetWatermarkText{COPYEDIT}
          \SetWatermarkScale{0.5}
          \SetWatermarkColor[gray]{0.9}
